### ISSUE TITLE
If any issues contact with me http://programing4fun.esy.es/

### ISSUE THREAD

**Issue by Alok255** [Alok255/php-mysql#1]
If any issues contact with me http://programing4fun.esy.es/

1) Goto my website and write in your issues in comment box
Thanks

**Comment by RSCipher001** [comment]
Can I comment issue here.

**Comment by Alok255** [comment]
yes bro

**Comment by RSCipher001** [comment]
Are you going to run this project further because I think zip file indicate the project is obsolete.
